### ISSUE TITLE
Upgrade is extremely slow.

### ISSUE THREAD

**Issue by ollydixon** [geoip-lite/node-geoip#247]
When upgrading the license on our docker builds it takes longer than 15 minutes.

We have other packages that are much heavier such as FFMPEG only taking a few seconds to install with no cache.

Seems like there is bug here? This should only take a few seconds.

<img width="1143" alt="slow" src="https://user-images.githubusercontent.com/6940726/204806432-8c9a7258-ab99-4767-acfc-6d73e1fdb19d.png">

**Comment by bluesmoon** [comment]
Updating the DB downloads it from the MaxMind servers. It all depends on how long that would take.  What happens if you try to download the DB using `curl`?
There isn't anything in the update code that controls the speed of the download.

AFAIK ffmpeg does not download any large files from a third party server.

**Comment by ollydixon** [comment]
@bluesmoon when running locally it takes around 2 minutes.

**Comment by ollydixon** [comment]
@bluesmoon I found the issue.

I have an M1 Mac and I was using the Intel Ubuntu image.

Now it only takes a minute. (unless you fixed some server stuff?)

```
// Old image
# FROM sitespeedio/node:ubuntu-20.04-nodejs-16.15.1

// Newer faster image
FROM arm64v8/ubuntu:20.04
```

**Comment by bluesmoon** [comment]
We don't control the server. It's run by MaxMind, and this project is not affiliated with MaxMind in any way.
