### ISSUE TITLE
Memory Usage Suggestion

### ISSUE THREAD

**Issue by jeremykentbgross** [geoip-lite/node-geoip#271]
The npm page says that the memory needed for this is significant and doesn't fit on some cloud provider instances.

It seems to me a big improvement for this then could be to store the data in a database like MongoDB, is there a reason why this isn't an option?

Many libraries like Session for example, allow the relevant connection information for several popular databases to be passed to the constructor.  Many if not most web servers will be using a database anyway, so it seems like having one shared instance of the data in the DB rather than using up memory on each instance would be preferable.

**Comment by bluesmoon** [comment]
We already have a database - the compacted dat files. We intentionally load the entire database into memory at startup for speed. The speed of this library is mainly due to everything already being in memory. That is the primary goal of this library. Having to call out to an external process like a database to fetch data would change the latency from nano/microseconds to milliseconds.
